language: python

cache: pip

python:
  - "3.7"

install:
  - pip install poetry codecov
  - poetry install

script:
  - make test BIN=""

after_success:
  - codecov

before_deploy:
  - poetry build

deploy:
  provider: script
  script: poetry publish --no-interaction --username=$PYPI_USERNAME --password=$PYPI_PASSWORD
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true
